name: tests

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -p'root' < scripts/Chinook_MySql.sql
          mysql -u root -p'root' -e 'SHOW TABLES;' Chinook

      - name: Test
        run: dotnet test --verbosity normal
